* Rahil Sayyad
* rahilsayyad389@gmail.com


In [1]:
#import libraries
import pandas as pd
import numpy as np
import seaborn as sns

## Load_dataset

In [2]:
df=sns.load_dataset("iris")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

## separate dependand((target)y) and independant(x) variable

In [5]:
x=df[["sepal_length","sepal_width","petal_length","petal_width"]]

In [6]:
y=df["species"]

## split the data in train and test side

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=13)

## fitting the naive bayes model GaussianNB

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
NB=GaussianNB()

In [10]:
#fit the model on traning data
NB.fit(x_train,y_train)

GaussianNB()

In [11]:
# predict the output using new observation
y_pred=NB.predict(x_test)

In [12]:
# check accuracy_score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9555555555555556


In [13]:
#confusion_matrix,classification_report
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[14  0  0]
 [ 0 12  0]
 [ 0  2 17]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.86      1.00      0.92        12
   virginica       1.00      0.89      0.94        19

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



## fitting the naive bayes model MultinomialNB 

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
MNB=MultinomialNB()

In [16]:
#fit the model on traning data
MNB.fit(x_train,y_train)

MultinomialNB()

In [17]:
# predict the output using new observation
y_pred=MNB.predict(x_test)

In [18]:
# check accuracy_score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.6444444444444445


In [19]:
#confusion_matrix,classification_report
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[14  0  0]
 [ 0 12  0]
 [ 0 16  3]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.43      1.00      0.60        12
   virginica       1.00      0.16      0.27        19

    accuracy                           0.64        45
   macro avg       0.81      0.72      0.62        45
weighted avg       0.85      0.64      0.59        45



## fitting the naive bayes model BernoulliNB 

In [20]:
from sklearn.naive_bayes import BernoulliNB

In [21]:
BNB=BernoulliNB()

In [22]:
#fit the model on traning data
BNB.fit(x_train,y_train)

BernoulliNB()

In [23]:
# predict the output using new observation
y_pred=BNB.predict(x_test)

In [24]:
# check accuracy_score
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.26666666666666666


In [25]:
#confusion_matrix,classification_report
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0 14  0]
 [ 0 12  0]
 [ 0 19  0]]
              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        14
  versicolor       0.27      1.00      0.42        12
   virginica       0.00      0.00      0.00        19

    accuracy                           0.27        45
   macro avg       0.09      0.33      0.14        45
weighted avg       0.07      0.27      0.11        45



C:\Users\Rahil\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Rahil\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Rahil\AppData\Roaming\Python\Python39\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
